### PR TITLE
feature/ Firebase 6.26.0

### PR DESCRIPTION
**Pull request by tomekfab**
Added binaries for 6.26.0 version

### CODE REVIEW

**Comment by squall2022** [comment]
@tomekfab I see that before we used this bundle id prefix `com.firebase.Firebase.*` and now we use `com.google.Firebase.*`, I guess this has changed?

**Comment by tomekfab** [comment]
@squall2022 Actually that's what was in the Carthage-tips readme I just followed the instructions.
Screenshot 2020-06-10 at 15 19 25

**Comment by tomekfab** [comment]
https://trello.com/c/PVY8e0yf

**Comment by squall2022** [comment]
@tomekfab Let's merge as we spoke (already done :D )
@azubala Do you know why we have difference between doc and zip in repo? Maybe it doesn't matter if we use `com.firebase.Firebase.*` or `com.google.Firebase.*`?

BTW @tomekfab seen bundle ids were now `com.firebase.Firebase-{{FrameworkName}}` so I guess Firebase team has finally fixed this 🌮

**Pull request merged**
